I am learning here that static initializers and service finder looked up classes loaded by Thread.currentThread().getContextClassLoader which in debugger is WebAppClassLoader requires the packages to be exported as otherwise it cannot load packages . I fixed a NoClassDefFoundError with RMAssertion but still am running into issues with policies service finder lookups. I am committing what I have for now for Fabian Issue number: Obtained from: Submitted by: Reviewed by:
svn path=/trunk/; revision=3981


Former-commit-id: 53708a513608f11f1b69b8cc725ca042d93f1179